version: '1'
services:
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./user:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    env_file:
      - .env/.env

  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    volumes:
      - ./product:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    env_file:
      - .env/.env


  # db:
  #   image: mysql:latest
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  #     - MYSQL_DATABASE=mydb
  #     - MYSQL_USER=myuser
  #     - MYSQL_PASSWORD=mypassword
  #   volumes:
  #     - ./db:/var/lib/mysql


  db:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - .env/.env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql












# version: '1'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8080:8080
#     volumes:
#       - ./app:/app
#     environment:
#       - NODE_ENV=development
#     depends_on:
#       - db

#   db:
#     image: mysql:latest
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_ROOT_PASSWORD=secret
#       - MYSQL_DATABASE=mydb
#       - MYSQL_USER=myuser
#       - MYSQL_PASSWORD=mypassword
#     volumes:
#       - ./db:/var/lib/mysql




# # version: '3'
# # services:
# #   user:
# #     build: ./user
# #     ports:
# #       - "8081:8080"
# #   product:
# #     build: ./product
# #     ports:
# #       - "8082:8080"