packageExtensions:
  class-transformer-validator@*:
    dependencies:
      class-transformer: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  markdownlint-cli@*:
    dependencies:
      deep-extend: "*"
  typeorm@*:
    dependencies:
      pg: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.2.1.cjs
